const KEY="upsc-mcq-revision-v1";
const sample=[
{id:"POL-001",subject:"Polity",topic:"Constitution",question:"The Constitution derives its authority directly from whom?",options:["Parliament","The President","The people of India","The Supreme Court"],answer:2,explanation:"The Constitution is founded on popular sovereignty: its authority ultimately derives from the people.",source:"Provided notes"},
{id:"POL-002",subject:"Polity",topic:"Constitution",question:"Which statement best describes the relationship between constitutional institutions and the Constitution?",options:["Institutions create the Constitution","Institutions derive power from the Constitution","Institutions are above the Constitution","Institutions derive power only from Parliament"],answer:1,explanation:"Constitutional institutions exercise powers that are conferred or structured by the Constitution.",source:"Provided notes"},
{id:"POL-003",subject:"Polity",topic:"Citizenship",question:"In the Constitution-related notes, the State–people relationship is associated with which concept?",options:["Federalism","Citizenship","Judicial review","Emergency"],answer:1,explanation:"The supplied notes identify citizenship as the State–people relationship.",source:"Provided notes"}
];
let data=JSON.parse(localStorage.getItem(KEY)||"null")||{questions:sample,attempts:{}};
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function qs(s){return document.querySelector(s)} function qsa(s){return [...document.querySelectorAll(s)]}
function show(id){qsa(".screen").forEach(x=>x.classList.remove("active"));qs("#"+id).classList.add("active");window.scrollTo(0,0);if(id==="dashboard")renderStats();if(id==="bank")renderBank()}
function attempted(id){return data.attempts[id]}
function renderStats(){const q=data.questions;const at=Object.values(data.attempts);const correct=at.filter(x=>x.correct).length;qs("#totalStat").textContent=q.length;qs("#unseenStat").textContent=q.filter(x=>!attempted(x.id)).length;qs("#wrongStat").textContent=q.filter(x=>attempted(x.id)&&!attempted(x.id).correct).length;qs("#accuracyStat").textContent=(at.length?Math.round(correct/at.length*100):0)+"%";qs("#bankSummary").textContent=`${q.length} questions • ${qsa(".tag").length? "":""} Your progress is saved on this device.`)}
let quiz={list:[],i:0};
function start(mode="all"){let list=data.questions;if(mode==="unseen")list=list.filter(q=>!attempted(q.id));if(mode==="wrong")list=list.filter(q=>attempted(q.id)&&!attempted(q.id).correct);if(!list.length){alert("No questions in this mode.");return}quiz={list:[...list].sort(()=>Math.random()-.5),i:0};show("quiz");renderQuestion()}
function renderQuestion(){const q=quiz.list[quiz.i];qs("#quizCounter").textContent=`${quiz.i+1} / ${quiz.list.length}`;qs("#progressBar").style.width=((quiz.i)/quiz.list.length*100)+"%";qs("#qSubject").textContent=q.subject||"General";qs("#qTopic").textContent=q.topic||"";qs("#questionText").textContent=q.question;qs("#feedback").hidden=true;qs("#nextBtn").hidden=true;const box=qs("#options");box.innerHTML="";q.options.forEach((o,n)=>{const b=document.createElement("button");b.className="option";b.textContent=String.fromCharCode(65+n)+". "+o;b.onclick=()=>answer(n);box.appendChild(b)})}
function answer(n){const q=quiz.list[quiz.i],correct=n===q.answer;data.attempts[q.id]={selected:n,correct,at:new Date().toISOString()};save();qsa(".option").forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add("correct");if(i===n&&!correct)b.classList.add("wrong")});const f=qs("#feedback");f.hidden=false;f.innerHTML=`<b>${correct?"✓ Correct":"✗ Incorrect"}</b>${q.explanation||"No explanation supplied."}`;qs("#nextBtn").hidden=false;renderStats()}
qs("#nextBtn").onclick=()=>{if(quiz.i<quiz.list.length-1){quiz.i++;renderQuestion()}else{alert("Quiz complete. Your progress has been saved.");show("dashboard")}};
function renderBank(){const term=(qs("#bankSearch").value||"").toLowerCase();const items=data.questions.filter(q=>(q.question+" "+q.subject+" "+q.topic).toLowerCase().includes(term));qs("#bankList").innerHTML=items.map(q=>`<div class="bank-item card"><h3>${escapeHtml(q.id)} • ${escapeHtml(q.subject||"General")}</h3><p>${escapeHtml(q.question)}</p><p style="margin-top:7px">Status: ${attempted(q.id)?(attempted(q.id).correct?"Correct":"Wrong"):"Unseen"}</p></div>`).join("")||'<p class="muted">No matching questions.</p>'}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
qsa("[data-action]").forEach(b=>b.addEventListener("click",()=>{const a=b.dataset.action;if(a==="home")show("dashboard");if(a==="start")start("all");if(a==="unseen")start("unseen");if(a==="wrong")start("wrong");if(a==="bank")show("bank");if(a==="import")show("import");if(a==="backup")show("backup")}));
qs("#bankSearch").addEventListener("input",renderBank);
qs("#importRun").onclick=()=>{try{const incoming=JSON.parse(qs("#importBox").value);if(!Array.isArray(incoming))throw Error("JSON must be an array.");incoming.forEach(validate);const map=new Map(data.questions.map(q=>[q.id,q]));incoming.forEach(q=>map.set(q.id,q));data.questions=[...map.values()];save();qs("#importMsg").hidden=false;qs("#importMsg").textContent=`Imported ${incoming.length} question(s). Total: ${data.questions.length}.`;renderStats()}catch(e){qs("#importMsg").hidden=false;qs("#importMsg").textContent="Import failed: "+e.message}}
function validate(q){if(!q.id||!q.question||!Array.isArray(q.options)||q.options.length<2||typeof q.answer!=="number"||q.answer<0||q.answer>=q.options.length)throw Error("Each question needs id, question, options and a valid numeric answer index.")}
qs("#exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="upsc-mcq-backup.json";a.click();URL.revokeObjectURL(a.href)}
qs("#restoreFile").onchange=async e=>{try{const obj=JSON.parse(await e.target.files[0].text());if(!obj.questions||!obj.attempts)throw Error("Invalid backup.");data=obj;save();qs("#restoreMsg").hidden=false;qs("#restoreMsg").textContent="Backup restored.";renderStats()}catch(err){qs("#restoreMsg").hidden=false;qs("#restoreMsg").textContent="Restore failed: "+err.message}}
qs("#resetBtn").onclick=()=>{if(confirm("Reset all attempt history?")){data.attempts={};save();renderStats();alert("Attempt history reset.")}};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;qs("#installBtn").hidden=false});qs("#installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};
renderStats();
alert("APP.JS IS WORKING");
